language: java

# Setting sudo to false will cause Travis to use Containers (default in the meantime)
sudo: required

services:
  - docker

before_install:
  - docker pull exasol/docker-db:latest
  - docker run --name exasoldb -p 127.0.0.1:8888:8888 -p 127.0.0.1:6583:6583 --detach --privileged --stop-timeout 120  exasol/docker-db:latest
  # - docker pull sath89/oracle-12c:novnc
  # - docker run --name oracledb -d -p 1521:1521 sath89/oracle-12c:novnc

matrix:
  include:
    - jdk: "oraclejdk8"
      env: MVN_ARGS=""

# build a jar with all dependencies. Will also run tests.
script:
  - CONFIG='/home/travis/build/hendrikcech/virtual-schemas/jdbc-adapter/integration-test-data/integration-test-travis.yaml'
  - while [ -z "$W_PW" ]; do W_PW=$(docker exec exasoldb cat /exa/etc/EXAConf | awk '/WritePasswd/{ print $3; }' | base64 -d); sleep 1; done; echo $W_PW
  - docker exec exasoldb cat /exa/etc/EXAConf
  - sed -i -e "s/BUCKET_FS_PASSWORD/$W_PW/" "$CONFIG"
  - cd jdbc-adapter
  - mvn $MVN_ARGS clean package
  - while [ $(docker exec exasoldb find /exa/data/bucketfs/bfsdefault/.dest | grep -c exaudfclient) -lt 1 ]; do sleep 1; done
  - mvn $MVN_ARGS pre-integration-test -DskipTests -Pit -Dintegrationtest.configfile="$CONFIG"
  - sleep 60
  # - while true; do free -hm; ps -Ao user,comm,%cpu,%mem,tty --sort=-pcpu | head -n 6; sleep 10; done &
  # - docker logs -f exasoldb &
  - while true; do sleep 60; docker exec exasoldb find / -iname '*SqlSession*' | tee - | xargs docker exec exasoldb cat; done &
  - mvn $MVN_ARGS verify -Pit -Dintegrationtest.configfile="$CONFIG"
