language: java

# Setting sudo to false will cause Travis to use Containers.
# To use Docker's privileged mode, we need to enable sudo.
sudo: required

services:
  - docker

before_install:
  - docker pull exasol/docker-db:latest
  - docker run --name exasoldb -p 8888:8888 -p 6583:6583 --detach --privileged --stop-timeout 120 exasol/docker-db:latest

matrix:
  include:
    - jdk: "oraclejdk8"
      env: MVN_ARGS=""

script:
  - cd jdbc-adapter
  - CONFIG='/home/travis/build/hendrikcech/virtual-schemas/jdbc-adapter/integration-test-data/integration-test-travis.yaml'
  # Wait for EXAConf to be generated
  - while [ -z "$W_PW" ]; do
      W_PW=$(docker exec exasoldb cat /exa/etc/EXAConf | awk '/WritePasswd/{ print $3; }' | base64 -d);
      sleep 1;
    done
  - sed -i -e "s/BUCKET_FS_PASSWORD/$W_PW/" "$CONFIG"
  - mvn $MVN_ARGS clean package
  # Wait for exaudfclient to be extracted and available
  - while [ $(docker exec exasoldb find /exa/data/bucketfs/bfsdefault/.dest -name exaudfclient -printf '.' | wc -c) -lt 1 ]; do sleep 1; done
  - mvn $MVN_ARGS pre-integration-test -DskipTests -Pit -Dintegrationtest.configfile="$CONFIG"
  # Wait another 60s for good measure
  - sleep 60
  - mvn $MVN_ARGS verify -Pit -Dintegrationtest.configfile="$CONFIG"
