language: java

# Setting sudo to false will cause Travis to use Containers (default in the meantime)
sudo: required

services:
  - docker

before_install:
  # - docker pull exasol/docker-db:latest
  # - docker run --name exasoldb -p 127.0.0.1:8563:8888 -p 127.0.0.1:2580:6583 --detach --privileged --stop-timeout 120  exasol/docker-db:latest

matrix:
  include:
    - jdk: "oraclejdk8"
      env: MVN_ARGS=""

# build a jar with all dependencies. Will also run tests.
script:
  - echo $PWD
  - ls
  # - cd jdbc-adapter
  # - mvn $MVN_ARGS clean package verify -Pit -Dintegrationtest.configfile=./jdbc-adapter/integration-test-data/integration-test-travis.yaml
