language: java

# Setting sudo to false will cause Travis to use Containers (default in the meantime)
sudo: required

services:
  - docker

before_install:
  - docker pull exasol/docker-db:latest
  - docker run --name exasoldb -p 127.0.0.1:8563:8888 -p 127.0.0.1:2580:6583 --detach --privileged --stop-timeout 120  exasol/docker-db:latest
  # - docker pull sath89/oracle-12c:novnc
  # - docker run --name oracledb -d -p 1521:1521 sath89/oracle-12c:novnc

matrix:
  include:
    - jdk: "oraclejdk8"
      env: MVN_ARGS=""

# build a jar with all dependencies. Will also run tests.
script:
  - CONFIG='/home/travis/build/hendrikcech/virtual-schemas/jdbc-adapter/integration-test-data/integration-test-travis.yaml'
  - while [ -z "$W_PW" ]; do W_PW=$(docker exec exasoldb cat /exa/etc/EXAConf | awk '/WritePasswd/{ print $3; }' | base64 -d); sleep 1; done; echo $W_PW
  - docker exec exasoldb cat /exa/etc/EXAConf
  - sed -i -e "s/BUCKET_FS_PASSWORD/$W_PW/" "$CONFIG"
  - cd jdbc-adapter
  - mvn $MVN_ARGS clean package
  - while [ $(docker exec exasoldb find /exa/data/bucketfs/bfsdefault/.dest | grep -c exaudfclient) -lt 1 ]; do sleep 1; done
  - curl -i -X PUT -T ../settings.cfg http://w:$W_PW@127.0.0.1:2580/default/drivers/jdbc/settings.cfg
  - mvn $MVN_ARGS verify -Pit -Dintegrationtest.configfile="$CONFIG"
  - R_PW=$(docker exec exasoldb cat /exa/etc/EXAConf | awk '/ReadPasswd/{ print $3; }' | base64 -d); echo $R_PW
  - curl -i http://r:$R_PW@127.0.0.1:2580/default
